[book]
authors = ["Mark Veltzer"]
language = "en"
src = "src"
title = "rsimagetag - Photo Tagging GUI Tool"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rsimagetag"
edit-url-template = "https://github.com/veltzer/rsimagetag/edit/master/docs/{path}"
